packages:
  - packages/*

catalogs:
  build:
    "tsdown": "0.19.0"
    "typescript": "5.9.3"
    "vite": "7.3.1"
  lint:
    "@gossi/config-eslint": ^1.3.1
    "@gossi/config-prettier": ^1.1.1
    "@gossi/config-template-lint": ^1.2.0
    "ember-template-lint": ^7.9.3
    "eslint": ^10.0.0
    "eslint-plugin-ember": ^12.7.5
    "eslint-plugin-qunit": ^8.2.5
    "prettier": 3.6.2
  test:
    "@testing-library/dom": "10.4.1"
    "@vitest/browser-playwright": "^4.0.17"
    "@vitest/coverage-istanbul": "^4.0.17"
    "@vitest/ui": "^4.0.17"
    "playwright": "^1.57.0"
    "vitest": "^4.0.17"
  lib:
    "@hokulea/core": ^0.9.1
    "@hokulea/theme-moana": ^0.4.0
    "es-toolkit": ^1.43.0
