name: Playwright Browser Install
description: Install Playwright
runs:
  using: composite
  steps:
    - name: Get installed Playwright version
      id: playwright-version
      run: |
        echo "PLAYWRIGHT_VERSION=$(sed -n '/^catalogs:/,/^[^ ]/p' pnpm-workspace.yaml | grep '^    "playwright":' | sed 's/.*: *["^]*//;s/["].*//' | head -n 1)" >> $GITHUB_ENV      run: |
      shell: bash

    - name: Cache playwright binaries
      uses: actions/cache@v5
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps chromium firefox webkit
      shell: bash
      if: steps.playwright-cache.outputs.cache-hit != 'true'

    - name: Install Browser Deps
      run: pnpm exec playwright install-deps chromium firefox webkit
      shell: bash
      if: steps.playwright-cache.outputs.cache-hit == 'true'
